runtime: nodejs
api_version: '1.0'
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.7
resources:
  cpu: 0.5
  memory_gb: 0.5
  disk_size_gb: 10